### ISSUE TITLE
Too much space before footer on mobile

### ISSUE THREAD

**Issue by opeah** [flaves/gleamm#24]
![Screenshot 2023-08-02 at 23 35 51](https://github.com/flaves/gleamm/assets/31569566/64c71f0b-3210-495e-a60f-2039a5a8c89a)

https://www.figma.com/file/LSUyejAxhAuzG83wTuopEj/gleamm?type=design&node-id=48%3A2446&mode=design&t=HCd7mY9Jod6LW2zc-1

**Comment by JohannBoumans** [comment]
I don't have this space issue too, i fixed this in a previous PR
